# Generated by Django 6.0.5 on 2026-05-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_role_order_id_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='profile_review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('approved', 'Approved')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='profile_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
