# Generated by Django 6.0.5 on 2026-05-23 18:04

import master.models.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_profile_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=master.models.tenant.tenant_upload_path),
        ),
    ]
