# Generated by Django 6.0.5 on 2026-05-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_add_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('tenant', 'name')},
        ),
        migrations.RemoveField(
            model_name='role',
            name='order_id',
        ),
    ]
